"""Install the tested BUBBLEGUM production program on a legacy CanMV K230.

Run this file with ``CanMV: Run Active File on K230``.  It only writes files
on the K230 SD card; it does not initialize the camera, UART, motor, servo, or
any other hardware.  A successful install creates ``/sdcard/main.py`` and
keeps the previous production file as ``/sdcard/main.py.bak``.
"""

import os

try:
    import uhashlib as hashlib
except ImportError:
    import hashlib


TARGET_PATH = "/sdcard/main.py"
TEMP_PATH = "/sdcard/main.py.new"
BACKUP_PATH = "/sdcard/main.py.bak"
EXPECTED_SIZE = 71099
EXPECTED_SHA256 = b'\xaf\xb3\x1d>\xa1b\x10J\xd67\xe8\x17\xfc\xba\x87^g\xb4x\xf5\x832\x864\xa1\xdaM\xfa4\x8f\xfa\r'
EXPECTED_SHA256_HEX = 'afb31d3ea162104ad637e817fcba875e67b478f583328634a1da4dfa348ffa0d'

PAYLOAD_CHUNKS = (
    b'"""K230 vision program for WRO traffic signs and parking markers.\n\nRun this standalone file from RAM first with the CanMV VS Code extension. It\nsends observations to the ESP32 through the pictured 40-pin UART header. The\nESP32 makes the steering and speed decisions. The values sent by this program\ndescribe image geometry, not distance in cm.\n\nThe filtering and temporal-tracking code stays importable on a host computer\nso its exact board logic can be tested without importing CanMV media modules.\nThe current production profile uses only red/green pillars; parking telemetry\nis experimental and disabled below.\n"""\n\nimport gc\n\ntry:\n    import ustruct as struct\nexcept ImportError:\n    import struct\n\n\nFRAME_WIDTH = 320\nFRAME_HEIGHT = 240\nPREVIEW_FPS = 15\nPREVIEW_DIVISOR = 4\n# Production default: no USB preview or overlay work in the driving loop.\n# Change this one value to True only for a tethered CanMV calibration session;\n# perception logic stays the same, but preview load can change timing/overrun\n# diagnostics a',
    b'nd must not be used for a driving performance claim.\nENABLE_IDE_PREVIEW = False\n\n# Parking control is disabled in the current ESP32 Obstacle profile. Keep the\n# extra full-frame colour scan off in production until the pair geometry has\n# been validated from the mounted camera. When explicitly enabled, protocol\n# "left/right" means image-left/image-right only, not a physical bay side.\nENABLE_EXPERIMENTAL_PARKING_TELEMETRY = False\n\n# K230 -> ESP32 vision link through the pictured 40-pin header. Physical pin\n# 11 is K230 GPIO5/UART2 TX, physical pin 13 is GPIO6/UART2 RX, and physical\n# pin 14 is GND. Cross TX/RX at the ESP32. Never connect a 40-pin-header power\n# pin between the boards; power the K230 separately through USB-C for IDE work\n# or its dedicated 8-24 V input for offline use.\nENABLE_UART_LINK = True\nUART_BAUDRATE = 115200\nUART_TX_GPIO = 5\nUART_RX_GPIO = 6\nUART_HEARTBEAT_INTERVAL_MS = 100\nPIPELINE_OVERRUN_AGE_MS = 80\nUART_OBSERVATION_FRAME_BYTES = 66\nUART_OBSERVATION_WIRE_TIME_MS = (\n    UART_OBSERVATI',
    b'ON_FRAME_BYTES * 10 * 1000 + UART_BAUDRATE - 1\n) // UART_BAUDRATE\n\n# Minimal embedded copy of protocol V1. The RAM-run tracker deliberately has\n# no sibling-file import because CanMV does not upload protocol/ automatically.\nUART_SYNC = b"\\xA5\\x5A"\nUART_VERSION = 1\nUART_TYPE_HEARTBEAT = 0x01\nUART_TYPE_OBSERVATION = 0x10\nUART_ROLE_K230 = 1\nUART_STATE_BOOT = 0\nUART_STATE_READY = 1\nUART_STATE_DEGRADED = 2\nUART_UNKNOWN_SEQUENCE = 0xFFFF\nUART_UNKNOWN_RANGE_MM = 0xFFFF\nUART_ERROR_LOOP_OVERRUN = 1 << 1\nUART_ERROR_CONFIG_INVALID = 1 << 7\nUART_FLAG_CAMERA_VALID = 1 << 0\nUART_FLAG_RED_PRESENT = 1 << 4\nUART_FLAG_GREEN_PRESENT = 1 << 5\nUART_FLAG_MAGENTA_LEFT_PRESENT = 1 << 6\nUART_FLAG_MAGENTA_RIGHT_PRESENT = 1 << 7\nUART_FLAG_PIPELINE_OVERRUN = 1 << 8\nUART_FLAG_EXPOSURE_UNSTABLE = 1 << 9\nUART_OBSERVATION_PAYLOAD_SIZE = 52\nUART_MAX_WRITE_ERRORS = 0xFFFF\n\n# Starting values from a properly illuminated desk scene. The competition-day\n# calibrator stores replacements on the SD card. Production tries the primary\n# file, then its',
    b' last-known-good backup, and finally these compiled defaults.\nCOLOR_CONFIG_LEGACY_MAGIC = "BUBBLEGUM_COLOR_V1"\nCOLOR_CONFIG_MAGIC = "BUBBLEGUM_COLOR_V2"\nCOLOR_CONFIG_PATH = "/sdcard/colorThresholds.cfg"\nCOLOR_CONFIG_BACKUP_PATH = "/sdcard/colorThresholds.bak"\nCOLOR_CONFIG_MAX_BYTES = 320\nDEFAULT_RED_LAB = (30, 72, 20, 68, 7, 58)\nDEFAULT_GREEN_LAB = (30, 75, -48, -14, 15, 68)\n# A calibrated threshold must stay clearly on the expected side of neutral\n# LAB A.  The margin rejects a white/grey sample that merely happens to be\n# separated from the red box, while retaining the latest field calibration\n# (red A 24..47, green A -33..-10) and the compiled diagnostic defaults.\nMIN_RED_A_LOW = 8\nMAX_GREEN_A_HIGH = -8\nRED_LAB = DEFAULT_RED_LAB\nGREEN_LAB = DEFAULT_GREEN_LAB\nMAGENTA_LAB = None\nRED_THRESHOLDS = [RED_LAB]\nGREEN_THRESHOLDS = [GREEN_LAB]\nMAGENTA_THRESHOLDS = []\n\n# The official traffic sign is 50 x 50 x 100 mm, so an unobstructed image is\n# expected to be upright and roughly twice as tall as it is wide.\nMIN_PIX',
    b"ELS = 24\nMIN_AREA = 32\nMIN_DENSITY_100 = 32\nMIN_BOTTOM_PX = 48\nMAX_CANDIDATES = 6\n# CanMV materializes find_blobs() before Python can copy a bounded subset. A\n# cluttered frame therefore fails closed before scoring/tracking and also caps\n# Python-side scan time. The mounted ROI and LAB calibration remain the real\n# controls for native allocation pressure.\nMAX_RAW_BLOBS_PER_COLOR = 32\n\n# Search only the configurable track region. The default is deliberately the\n# full frame: cropping at the old base threshold would cut the top off a real\n# pillar whose base is valid. Narrow this only from mounted-camera field images.\n# CanMV's ROI is (x, y, width, height).\nTRACK_ROI_X = 0\nTRACK_ROI_Y = 0\nTRACK_ROI_W = FRAME_WIDTH\nTRACK_ROI_H = FRAME_HEIGHT - TRACK_ROI_Y\nTRACK_ROI = (TRACK_ROI_X, TRACK_ROI_Y, TRACK_ROI_W, TRACK_ROI_H)\n\n# A valid sign must end on the searched track/ground region. Keeping this\n# separate from TRACK_ROI makes an intentional track calibration visible and\n# preserves fail-closed behavior if the ROI ",
    b'is later widened for debugging.\nGROUND_BASE_MIN_Y = MIN_BOTTOM_PX\nGROUND_BASE_MAX_Y = TRACK_ROI_Y + TRACK_ROI_H - 1\n\n# Edge clipping relaxes aspect ratio only for plausible close pillars. These\n# hard limits still reject a wall/card that reaches an image edge.\nHARD_MAX_WIDTH_PERCENT = 60\nHARD_MAX_AREA_PERCENT = 35\nRELAXED_MAX_WIDTH_PERCENT = 50\nRELAXED_MAX_AREA_PERCENT = 22\nRELAXED_MIN_DENSITY_100 = 55\n\n# This dimensionless score combines upright geometry, fill, bounded size, and\n# ground position below. It is intentionally not a LAB calibration value.\n# Raise it only after reviewing raw-candidate overlays on the mounted camera.\nMIN_CANDIDATE_QUALITY = 45\n\n# Association limits are deliberately hard-capped. A large nearby box must\n# not make the gate wide enough to jump to another same-color pillar.\nMAX_ASSOC_X_PX = 48\nMAX_ASSOC_BASE_PX = 72\nMAX_ASSOC_AREA_RATIO = 3\n\n# A report requires consecutive associated detections. Briefly retain a\n# confirmed target for overlays through an occlusion, but stale memory is',
    b'\n# never put on UART and therefore never controls steering.\nTRACK_CONFIRM_HITS = 3\nTRACK_OCCLUSION_MEMORY_FRAMES = 2\nUNCONFIRMED_MISS_LIMIT = 1\n\n# This is a fail-closed sanity check, not a final track calibration. The dark\n# desk failure had L upper-quartile near 0-3 and L max near 12. A valid frame\n# needs both usable midtones and at least one properly exposed highlight. At\n# the measured 46 FPS, checking every three frames bounds a newly detected\n# exposure failure to roughly 65 ms without doing a full statistics pass on\n# every image.\nVISION_CHECK_INTERVAL = 3\nMIN_VISION_L_UQ = 8\nMIN_VISION_L_MAX = 25\n\n# Candidate tuple indexes. Only primitive values survive beyond a snapshot;\n# CanMV Blob objects are never retained.\nC_X = 0\nC_Y = 1\nC_W = 2\nC_H = 3\nC_PIXELS = 4\nC_DENSITY = 5\nC_CX = 6\nC_BASE = 7\nC_Q = 8\nC_FLAGS = 9\nC_FLAG_RELAXED_SHAPE = 1 << 0\nC_FLAG_SIDE_CLIPPED = 1 << 1\nC_FLAG_NO_GROUND_SUPPORT = 1 << 2\n\n# New targets must visibly terminate on the bright, mostly neutral track mat.\n# This prevents an upri',
    b'ght red/green item beyond the 100 mm black wall (for\n# example clothing) from becoming a steering instruction.  The 3 x 3 fan is\n# deliberately wider than a small far pillar and tolerates one complete row\n# landing on an official blue/orange/yellow marking.\nGROUND_SUPPORT_ROW_OFFSETS = (2, 5, 9)\nGROUND_SUPPORT_MIN_SAMPLES = 6\n\n\ndef clamp(value, low, high):\n    if value < low:\n        return low\n    if value > high:\n        return high\n    return value\n\n\ndef validate_lab_threshold(threshold):\n    """Return a normalized six-value LAB threshold or raise ValueError."""\n\n    if not isinstance(threshold, (tuple, list)) or len(threshold) != 6:\n        raise ValueError("LAB threshold must contain six integers")\n\n    normalized = []\n    for value in threshold:\n        # bool is an int on both CPython and MicroPython, but accepting it in a\n        # persisted calibration would hide a damaged or hand-edited file.\n        if isinstance(value, bool) or not isinstance(value, int):\n            raise ValueError("LAB threshol',
    b'd values must be integers")\n        normalized.append(value)\n\n    limits = ((0, 100), (0, 100)) + ((-128, 127),) * 4\n    for value, bounds in zip(normalized, limits):\n        if not bounds[0] <= value <= bounds[1]:\n            raise ValueError("LAB threshold value outside sensor range")\n    for low_index in (0, 2, 4):\n        if normalized[low_index] >= normalized[low_index + 1]:\n            raise ValueError("LAB threshold needs a non-zero range")\n    return tuple(normalized)\n\n\ndef validate_color_threshold_pair(red_lab, green_lab):\n    """Reject structurally valid but unsafe red/green configurations."""\n\n    red_lab = validate_lab_threshold(red_lab)\n    green_lab = validate_lab_threshold(green_lab)\n    for threshold in (red_lab, green_lab):\n        if threshold[1] - threshold[0] > 90:\n            raise ValueError("LAB luminance threshold is implausibly wide")\n        if threshold[3] - threshold[2] > 110:\n            raise ValueError("LAB A threshold is implausibly wide")\n        if threshold[5] - threshold[4]',
    b' > 110:\n            raise ValueError("LAB B threshold is implausibly wide")\n    if red_lab[2] < MIN_RED_A_LOW:\n        raise ValueError("red LAB A range is not clearly positive")\n    if green_lab[3] > MAX_GREEN_A_HIGH:\n        raise ValueError("green LAB A range is not clearly negative")\n    # These two competition colours separate primarily on LAB A. Overlapping\n    # bands let the same pixels become both a red and a green target.\n    if red_lab[2] <= green_lab[3]:\n        raise ValueError("red and green LAB A thresholds overlap")\n    return red_lab, green_lab\n\n\ndef thresholds_overlap(first, second):\n    return all(\n        not (first[index + 1] < second[index] or second[index + 1] < first[index])\n        for index in (0, 2, 4)\n    )\n\n\ndef validate_color_thresholds(red_lab, green_lab, magenta_lab=None):\n    red_lab, green_lab = validate_color_threshold_pair(red_lab, green_lab)\n    if magenta_lab is None:\n        return red_lab, green_lab, None\n    magenta_lab = validate_lab_threshold(magenta_lab)\n    if mage',
    b'nta_lab[1] - magenta_lab[0] > 90:\n        raise ValueError("magenta LAB luminance threshold is implausibly wide")\n    if magenta_lab[3] - magenta_lab[2] > 110:\n        raise ValueError("magenta LAB A threshold is implausibly wide")\n    if magenta_lab[5] - magenta_lab[4] > 110:\n        raise ValueError("magenta LAB B threshold is implausibly wide")\n    if thresholds_overlap(red_lab, magenta_lab):\n        raise ValueError("red and magenta LAB thresholds overlap")\n    if thresholds_overlap(green_lab, magenta_lab):\n        raise ValueError("green and magenta LAB thresholds overlap")\n    return red_lab, green_lab, magenta_lab\n\n\ndef magenta_detection_thresholds(red_lab, green_lab, magenta_lab):\n    """Build a bounded darker-magenta companion without changing calibration.\n\n    The saved V2 sample separates red from magenta mainly by luminance, so\n    blindly lowering magenta L would also classify calibrated red pixels as\n    magenta. Instead, any darker companion keeps only a calibrated chroma tail\n    that lies who',
    b'lly outside both pillar thresholds. Its L extension is at\n    most one calibrated magenta L-band width. If no such tail exists, the\n    original threshold is returned unchanged rather than guessing.\n\n    This affects production detection only. It deliberately does not weaken\n    calibration validation or rewrite the persisted file.\n    """\n\n    red_lab, green_lab, magenta_lab = validate_color_thresholds(\n        red_lab,\n        green_lab,\n        magenta_lab,\n    )\n    if magenta_lab is None:\n        return []\n\n    thresholds = [magenta_lab]\n    shadow_l_high = magenta_lab[0] - 1\n    calibrated_l_span = magenta_lab[1] - magenta_lab[0]\n    shadow_l_low = max(0, magenta_lab[0] - calibrated_l_span)\n    if shadow_l_low >= shadow_l_high:\n        return thresholds\n\n    best = None\n    best_span = -1\n    # Look for an upper or lower tail on A and then B. Requiring one channel\n    # to be wholly outside both pillar bands guarantees three-dimensional LAB\n    # boxes cannot overlap, even though their luminance bands n',
    b'ow may.\n    for channel_index in (2, 4):\n        upper_low = max(\n            magenta_lab[channel_index],\n            red_lab[channel_index + 1] + 1,\n            green_lab[channel_index + 1] + 1,\n        )\n        upper_high = magenta_lab[channel_index + 1]\n        if upper_low < upper_high:\n            candidate = list(magenta_lab)\n            candidate[0] = shadow_l_low\n            candidate[1] = shadow_l_high\n            candidate[channel_index] = upper_low\n            candidate[channel_index + 1] = upper_high\n            span = upper_high - upper_low\n            if span > best_span:\n                best = tuple(candidate)\n                best_span = span\n\n        lower_low = magenta_lab[channel_index]\n        lower_high = min(\n            magenta_lab[channel_index + 1],\n            red_lab[channel_index] - 1,\n            green_lab[channel_index] - 1,\n        )\n        if lower_low < lower_high:\n            candidate = list(magenta_lab)\n            candidate[0] = shadow_l_low\n            candidate[1] = sha',
    b'dow_l_high\n            candidate[channel_index] = lower_low\n            candidate[channel_index + 1] = lower_high\n            span = lower_high - lower_low\n            if span > best_span:\n                best = tuple(candidate)\n                best_span = span\n\n    if best is None:\n        return thresholds\n    best = validate_lab_threshold(best)\n    if thresholds_overlap(best, red_lab) or thresholds_overlap(\n        best,\n        green_lab,\n    ):\n        # Defensive guard for future edits to the tail construction.\n        return thresholds\n    thresholds.append(best)\n    return thresholds\n\n\ndef format_color_thresholds(red_lab, green_lab, magenta_lab=None):\n    """Return the small, deterministic on-card calibration format."""\n\n    red_lab, green_lab, magenta_lab = validate_color_thresholds(\n        red_lab, green_lab, magenta_lab\n    )\n    if magenta_lab is None:\n        return "%s\\nRED=%s\\nGREEN=%s\\n" % (\n            COLOR_CONFIG_LEGACY_MAGIC,\n            ",".join(str(value) for value in red_lab),\n        ',
    b'    ",".join(str(value) for value in green_lab),\n        )\n    return "%s\\nRED=%s\\nGREEN=%s\\nMAGENTA=%s\\n" % (\n        COLOR_CONFIG_MAGIC,\n        ",".join(str(value) for value in red_lab),\n        ",".join(str(value) for value in green_lab),\n        ",".join(str(value) for value in magenta_lab),\n    )\n\n\ndef parse_color_thresholds(text):\n    """Strictly parse one red/green calibration file."""\n\n    if not isinstance(text, str):\n        raise ValueError("colour config must be text")\n    lines = [line.strip() for line in text.splitlines() if line.strip()]\n    if not lines or lines[0] not in (\n        COLOR_CONFIG_LEGACY_MAGIC,\n        COLOR_CONFIG_MAGIC,\n    ):\n        raise ValueError("wrong colour config header or line count")\n    expected_keys = (\n        ("RED", "GREEN")\n        if lines[0] == COLOR_CONFIG_LEGACY_MAGIC\n        else ("RED", "GREEN", "MAGENTA")\n    )\n    if len(lines) != len(expected_keys) + 1:\n        raise ValueError("wrong colour config header or line count")\n\n    values = {}\n    for line ',
    b'in lines[1:]:\n        if "=" not in line:\n            raise ValueError("malformed colour config line")\n        key, encoded = line.split("=", 1)\n        if key not in expected_keys or key in values:\n            raise ValueError("unknown or duplicate colour config key")\n        parts = encoded.split(",")\n        if len(parts) != 6:\n            raise ValueError("colour config threshold needs six values")\n        try:\n            threshold = tuple(int(part) for part in parts)\n        except (TypeError, ValueError):\n            raise ValueError("colour config contains a non-integer")\n        values[key] = validate_lab_threshold(threshold)\n\n    if any(key not in values for key in expected_keys):\n        raise ValueError("colour config is missing a required threshold")\n    return validate_color_thresholds(\n        values["RED"], values["GREEN"], values.get("MAGENTA")\n    )\n\n\ndef read_color_thresholds(path):\n    with open(path, "r") as handle:\n        text = handle.read(COLOR_CONFIG_MAX_BYTES + 1)\n    if len(text) >',
    b' COLOR_CONFIG_MAX_BYTES:\n        raise ValueError("colour config is unexpectedly large")\n    return parse_color_thresholds(text)\n\n\ndef load_color_thresholds(\n    primary_path=COLOR_CONFIG_PATH,\n    backup_path=COLOR_CONFIG_BACKUP_PATH,\n):\n    """Load primary, backup, or diagnostic compiled defaults in that order."""\n\n    for label, path in (("SD primary", primary_path), ("SD backup", backup_path)):\n        try:\n            red_lab, green_lab, magenta_lab = read_color_thresholds(path)\n            return red_lab, green_lab, magenta_lab, "%s %s" % (label, path)\n        except (OSError, ValueError) as error:\n            print("colour config unavailable:", path, error)\n    return DEFAULT_RED_LAB, DEFAULT_GREEN_LAB, None, "built-in defaults"\n\n\ndef persisted_pillar_config_ready(source):\n    """Return True only for a structurally valid persisted red/green config.\n\n    The built-in desk thresholds remain useful for displaying a diagnostic\n    preview, but they are never authority for obstacle steering.  Magenta is\n   ',
    b' optional because the current obstacle controller is pillar-only; a V2\n    file enables parking-pair observations without changing this readiness\n    gate.\n    """\n\n    if not isinstance(source, str):\n        return False\n    return source.startswith("SD primary ") or source.startswith("SD backup ")\n\n\ndef uart_crc16_ccitt_false(data):\n    """Return protocol V1 CRC-16/CCITT-FALSE."""\n\n    crc = 0xFFFF\n    for byte in data:\n        crc ^= int(byte) << 8\n        for _ in range(8):\n            if crc & 0x8000:\n                crc = ((crc << 1) ^ 0x1021) & 0xFFFF\n            else:\n                crc = (crc << 1) & 0xFFFF\n    return crc\n\n\ndef uart_build_frame(message_type, sequence, timestamp_ms, payload=b""):\n    """Build one self-delimiting V1 frame, byte-identical to protocol/."""\n\n    payload = bytes(payload)\n    if not 0 <= int(message_type) <= 0xFF:\n        raise ValueError("UART message type outside uint8")\n    if not 0 <= int(sequence) <= 0xFFFF:\n        raise ValueError("UART sequence outside uint16")\n   ',
    b' if not 0 <= int(timestamp_ms) <= 0xFFFFFFFF:\n        raise ValueError("UART timestamp outside uint32")\n    if len(payload) > 64:\n        raise ValueError("UART payload exceeds 64 bytes")\n    body = struct.pack(\n        "<BBHIH",\n        UART_VERSION,\n        int(message_type),\n        int(sequence),\n        int(timestamp_ms),\n        len(payload),\n    ) + payload\n    return UART_SYNC + body + struct.pack(\n        "<H",\n        uart_crc16_ccitt_false(body),\n    )\n\n\ndef uart_pack_heartbeat(\n    state,\n    error_flags=0,\n    last_rx_sequence=UART_UNKNOWN_SEQUENCE,\n    loop_rate_hz_x10=0,\n):\n    """Pack the fixed eight-byte K230 heartbeat payload."""\n\n    if state < 0 or state > 3:\n        raise ValueError("UART heartbeat state outside 0..3")\n    if error_flags < 0 or error_flags > 0xFF:\n        raise ValueError("UART heartbeat error flags outside uint8")\n    if last_rx_sequence < 0 or last_rx_sequence > 0xFFFF:\n        raise ValueError("UART heartbeat RX sequence outside uint16")\n    if loop_rate_hz_x10 < 0 or ',
    b'loop_rate_hz_x10 > 0xFFFF:\n        raise ValueError("UART heartbeat rate outside uint16")\n    return struct.pack(\n        "<BBHHH",\n        UART_ROLE_K230,\n        int(state),\n        int(error_flags),\n        int(last_rx_sequence),\n        int(loop_rate_hz_x10),\n    )\n\n\ndef _uart_round_ratio(numerator, denominator):\n    if denominator <= 0:\n        raise ValueError("UART normalization denominator must be positive")\n    if numerator < 0:\n        return -((-numerator + denominator // 2) // denominator)\n    return (numerator + denominator // 2) // denominator\n\n\ndef uart_blob_from_pixels(x, y, width, height, quality):\n    """Normalize one current tracker box into a protocol V1 blob slot."""\n\n    x = int(x)\n    y = int(y)\n    width = int(width)\n    height = int(height)\n    quality = int(quality)\n    if width <= 0 or height <= 0:\n        raise ValueError("UART present blob dimensions must be positive")\n    if (\n        x < 0\n        or y < 0\n        or x + width > FRAME_WIDTH\n        or y + height > FRAME_HEIGHT\n ',
    b'   ):\n        raise ValueError("UART blob lies outside the frame")\n    if quality < 0 or quality > 100:\n        raise ValueError("UART blob quality outside 0..100")\n\n    center_x_twice = 2 * x + width - 1\n    center_x = _uart_round_ratio(\n        (center_x_twice - (FRAME_WIDTH - 1)) * 10000,\n        FRAME_WIDTH - 1,\n    )\n    bottom_y = _uart_round_ratio(\n        (y + height - 1) * 10000,\n        FRAME_HEIGHT - 1,\n    )\n    width_norm = min(\n        10000,\n        _uart_round_ratio(width * 10000, FRAME_WIDTH),\n    )\n    height_norm = min(\n        10000,\n        _uart_round_ratio(height * 10000, FRAME_HEIGHT),\n    )\n    confidence = 1 + (quality * 999) // 100\n    return (center_x, bottom_y, width_norm, height_norm, confidence)\n\n\ndef uart_target_slot(target):\n    """Return a slot only for a confirmed target hit in the current frame."""\n\n    if target is None or not target.actionable():\n        return None\n    return uart_blob_from_pixels(\n        target.x,\n        target.y,\n        target.w,\n        target.h,\n ',
    b'       target.q,\n    )\n\n\ndef uart_parking_pair_slots(left_target, right_target):\n    """Return two ordered current slots, or fail closed as an absent pair."""\n\n    if left_target is None or right_target is None:\n        return None, None\n    if not left_target.actionable() or not right_target.actionable():\n        return None, None\n    if left_target.center_x() >= right_target.center_x():\n        return None, None\n    if left_target.x + left_target.w > right_target.x:\n        return None, None\n    if (\n        left_target.y + left_target.h <= right_target.y\n        or right_target.y + right_target.h <= left_target.y\n    ):\n        return None, None\n    return uart_target_slot(left_target), uart_target_slot(right_target)\n\n\ndef _uart_pack_blob(slot):\n    if slot is None:\n        return struct.pack("<hHHHH", 0, 0, 0, 0, 0)\n    if len(slot) != 5:\n        raise ValueError("UART blob slot must have five fields")\n    return struct.pack(\n        "<hHHHH",\n        int(slot[0]),\n        int(slot[1]),\n        int(slot[2',
    b']),\n        int(slot[3]),\n        int(slot[4]),\n    )\n\n\ndef uart_pack_tracker_observation(\n    camera_valid,\n    frame_quality,\n    processing_age_ms,\n    red_target=None,\n    green_target=None,\n    pipeline_overrun=False,\n    magenta_left_target=None,\n    magenta_right_target=None,\n    exposure_unstable=None,\n):\n    """Pack current actionable targets; invalid/stale inputs become zeros.\n\n    Magenta slots are intentionally populated only by a jointly confirmed\n    parking pair.  Callers must not assign an unpaired magenta blob to either\n    side.  ``exposure_unstable`` defaults to the legacy behavior for host API\n    compatibility, while the live loop supplies the actual failure reason.\n    """\n\n    frame_quality = int(frame_quality)\n    processing_age_ms = int(processing_age_ms)\n    if frame_quality < 0 or frame_quality > 100:\n        raise ValueError("UART frame quality outside 0..100")\n    if processing_age_ms < 0 or processing_age_ms > 0xFFFF:\n        raise ValueError("UART processing age outside uint16")',
    b'\n\n    flags = 0\n    if pipeline_overrun:\n        flags |= UART_FLAG_PIPELINE_OVERRUN\n    if exposure_unstable is None:\n        exposure_unstable = not camera_valid\n    if camera_valid:\n        flags |= UART_FLAG_CAMERA_VALID\n        red = uart_target_slot(red_target)\n        green = uart_target_slot(green_target)\n        magenta_left, magenta_right = uart_parking_pair_slots(\n            magenta_left_target,\n            magenta_right_target,\n        )\n        if red is not None:\n            flags |= UART_FLAG_RED_PRESENT\n        if green is not None:\n            flags |= UART_FLAG_GREEN_PRESENT\n        # A lone magenta target has no safe left/right identity in protocol\n        # V1.  Drop both unless the pair tracker supplied two fresh members.\n        if magenta_left is None or magenta_right is None:\n            magenta_left = None\n            magenta_right = None\n        else:\n            flags |= UART_FLAG_MAGENTA_LEFT_PRESENT\n            flags |= UART_FLAG_MAGENTA_RIGHT_PRESENT\n    else:\n        # A failed',
    b' camera/config/scan gate never carries a prior target.\n        if exposure_unstable:\n            flags |= UART_FLAG_EXPOSURE_UNSTABLE\n        frame_quality = 0\n        red = None\n        green = None\n        magenta_left = None\n        magenta_right = None\n\n    payload = struct.pack(\n        "<HbBHhhH",\n        flags,\n        0,\n        frame_quality,\n        processing_age_ms,\n        0,\n        0,\n        UART_UNKNOWN_RANGE_MM,\n    )\n    payload += _uart_pack_blob(red)\n    payload += _uart_pack_blob(green)\n    payload += _uart_pack_blob(magenta_left)\n    payload += _uart_pack_blob(magenta_right)\n    if len(payload) != UART_OBSERVATION_PAYLOAD_SIZE:\n        raise RuntimeError("UART observation payload size changed")\n    return payload\n\n\ndef uart_frame_quality(vision_ok, l_uq, l_max):\n    """Map current luminance statistics to the protocol\'s 0..100 field."""\n\n    if not vision_ok:\n        return 0\n    return clamp((int(l_uq) + int(l_max)) // 2, 0, 100)\n\n\nclass UartFrameWriter:\n    """One bounded, non-throwing',
    b' writer with a shared V1 sequence counter."""\n\n    def __init__(self, uart, initial_sequence=0):\n        if initial_sequence < 0 or initial_sequence > 0xFFFF:\n            raise ValueError("initial UART sequence outside uint16")\n        self.uart = uart\n        self.sequence = int(initial_sequence)\n        self.frames_sent = 0\n        self.write_errors = 0\n        self.write_error_streak = 0\n\n    def _record_error(self):\n        self.write_errors = min(\n            UART_MAX_WRITE_ERRORS,\n            self.write_errors + 1,\n        )\n        self.write_error_streak = min(255, self.write_error_streak + 1)\n\n    def send(self, message_type, timestamp_ms, payload):\n        frame = uart_build_frame(\n            message_type,\n            self.sequence,\n            timestamp_ms,\n            payload,\n        )\n        try:\n            written = self.uart.write(frame)\n        except Exception:\n            self._record_error()\n            return False\n        if written is None or int(written) != len(frame):\n            s',
    b'elf._record_error()\n            return False\n\n        self.sequence = (self.sequence + 1) & 0xFFFF\n        self.frames_sent = min(0xFFFFFFFF, self.frames_sent + 1)\n        self.write_error_streak = 0\n        return True\n\n    def close(self):\n        try:\n            self.uart.deinit()\n        except Exception:\n            pass\n\n\ndef open_uart_link():\n    """Configure the LushanPi 40-pin UART2 route and framed writer."""\n\n    from machine import FPIOA, UART\n\n    fpioa = FPIOA()\n    fpioa.set_function(UART_TX_GPIO, FPIOA.UART2_TXD)\n    fpioa.set_function(UART_RX_GPIO, FPIOA.UART2_RXD)\n    uart = UART(\n        UART.UART2,\n        baudrate=UART_BAUDRATE,\n        bits=UART.EIGHTBITS,\n        parity=UART.PARITY_NONE,\n        stop=UART.STOPBITS_ONE,\n    )\n    return UartFrameWriter(uart)\n\n\ndef uart_send_boot_heartbeat(uart_link, timestamp_ms):\n    """Start/rebase one UART session before camera initialization blocks."""\n\n    return uart_link.send(\n        UART_TYPE_HEARTBEAT,\n        int(timestamp_ms) & 0xFFFFFFFF,\n ',
    b'       uart_pack_heartbeat(UART_STATE_BOOT),\n    )\n\n\ndef vision_quality(statistics):\n    """Return ``(ok, l_uq, l_max)`` for a CanMV statistics object."""\n\n    l_uq = int(statistics.l_uq())\n    l_max = int(statistics.l_max())\n    ok = l_uq >= MIN_VISION_L_UQ and l_max >= MIN_VISION_L_MAX\n    return ok, l_uq, l_max\n\n\ndef uart_health_status(exposure_ok, calibration_ready, scan_ok, pipeline_overrun):\n    """Map current perception evidence to heartbeat state and error flags."""\n\n    error_flags = 0\n    if not calibration_ready:\n        error_flags |= UART_ERROR_CONFIG_INVALID\n    if pipeline_overrun:\n        error_flags |= UART_ERROR_LOOP_OVERRUN\n    ready = (\n        exposure_ok\n        and calibration_ready\n        and scan_ok\n        and not pipeline_overrun\n    )\n    return UART_STATE_READY if ready else UART_STATE_DEGRADED, error_flags\n\n\ndef candidate_rank(candidate):\n    # Ground contact is the depth proxy available from one camera. Make it the\n    # primary key so a clean far pillar cannot hide a nearer sa',
    b'me-colour one;\n    # bounded 0..100 quality only breaks ties at the same base row.\n    return candidate[C_BASE] * 101 + clamp(candidate[C_Q], 0, 100)\n\n\ndef track_roi_is_valid():\n    """Reject a bad hand-edited ROI before passing it to CanMV."""\n\n    if TRACK_ROI_W <= 0 or TRACK_ROI_H <= 0:\n        return False\n    if TRACK_ROI_X < 0 or TRACK_ROI_Y < 0:\n        return False\n    if TRACK_ROI_X + TRACK_ROI_W > FRAME_WIDTH:\n        return False\n    if TRACK_ROI_Y + TRACK_ROI_H > FRAME_HEIGHT:\n        return False\n    return (\n        TRACK_ROI_Y <= GROUND_BASE_MIN_Y\n        and GROUND_BASE_MIN_Y <= GROUND_BASE_MAX_Y\n        and GROUND_BASE_MAX_Y < TRACK_ROI_Y + TRACK_ROI_H\n    )\n\n\ndef base_on_ground(center_x, base_y):\n    """Return True only when a blob base lies in the configured track ROI."""\n\n    if not track_roi_is_valid():\n        return False\n    roi_right = TRACK_ROI_X + TRACK_ROI_W - 1\n    if center_x < TRACK_ROI_X or center_x > roi_right:\n        return False\n    return GROUND_BASE_MIN_Y <= base_y <= GRO',
    b'UND_BASE_MAX_Y\n\n\ndef track_floor_pixel(pixel):\n    """Return True for a bright, mostly neutral RGB track-mat pixel."""\n\n    if not isinstance(pixel, (tuple, list)) or len(pixel) < 3:\n        return False\n    try:\n        red = int(pixel[0])\n        green = int(pixel[1])\n        blue = int(pixel[2])\n    except (TypeError, ValueError):\n        return False\n    if min(red, green, blue) < 0 or max(red, green, blue) > 255:\n        return False\n    darkest = min(red, green, blue)\n    brightest = max(red, green, blue)\n    return (\n        red + green + blue >= 180\n        and brightest > 0\n        and 5 * darkest >= 3 * brightest\n    )\n\n\ndef candidate_has_ground_support(image, candidate):\n    """Check a bounded 3 x 3 fan of pixels just below a pillar candidate."""\n\n    if image is None or candidate is None:\n        return False\n    center_x = candidate[C_CX]\n    base_y = candidate[C_BASE]\n    span = clamp(max(6, candidate[C_W]), 6, 32)\n    floor_samples = 0\n    total_samples = 0\n    for row_offset in GROUND_SUPPORT_',
    b'ROW_OFFSETS:\n        sample_y = base_y + row_offset\n        if sample_y < 0 or sample_y >= FRAME_HEIGHT:\n            continue\n        for sample_x in (center_x - span, center_x, center_x + span):\n            if sample_x < 0 or sample_x >= FRAME_WIDTH:\n                continue\n            try:\n                pixel = image.get_pixel(sample_x, sample_y)\n            except (AttributeError, OSError, TypeError, ValueError):\n                return False\n            total_samples += 1\n            if track_floor_pixel(pixel):\n                floor_samples += 1\n    return (\n        total_samples >= GROUND_SUPPORT_MIN_SAMPLES\n        and 3 * floor_samples >= 2 * total_samples\n    )\n\n\ndef copy_blob(blob):\n    """Copy and validate one blob, returning a fixed primitive tuple."""\n\n    x = int(blob.x())\n    y = int(blob.y())\n    width = int(blob.w())\n    height = int(blob.h())\n    pixels = int(blob.pixels())\n    density_100 = int(blob.density() * 100)\n\n    if width < 4 or height < 8 or pixels < MIN_PIXELS:\n        return No',
    b'ne\n    if density_100 < MIN_DENSITY_100:\n        return None\n\n    right = x + width - 1\n    base = y + height - 1\n    if x < 0 or y < 0 or right >= FRAME_WIDTH or base >= FRAME_HEIGHT:\n        return None\n    center_x = x + (width - 1) // 2\n    if not base_on_ground(center_x, base):\n        return None\n\n    touches_top = y <= 3\n    touches_bottom = base >= FRAME_HEIGHT - 4\n    touches_side = x <= 3 or right >= FRAME_WIDTH - 4\n    candidate_flags = C_FLAG_SIDE_CLIPPED if touches_side else 0\n    box_area = width * height\n    frame_area = FRAME_WIDTH * FRAME_HEIGHT\n\n    if width * 100 > HARD_MAX_WIDTH_PERCENT * FRAME_WIDTH:\n        return None\n    if box_area * 100 > HARD_MAX_AREA_PERCENT * frame_area:\n        return None\n\n    # Normal view: about 2:1, with generous perspective tolerance. A close\n    # pillar clipped by an image edge is allowed a wider apparent shape only\n    # when it is dense and still bounded in width/area.\n    aspect_100 = (100 * height) // width\n    min_aspect_100 = 115\n    large_edge_candi',
    b'date = (\n        width >= FRAME_WIDTH // 12 and height >= FRAME_HEIGHT // 8\n    )\n    if touches_bottom and large_edge_candidate:\n        min_aspect_100 = 55\n    elif touches_top and large_edge_candidate:\n        min_aspect_100 = 75\n    max_aspect_100 = 1200 if touches_side else 600\n    if aspect_100 < min_aspect_100 or aspect_100 > max_aspect_100:\n        return None\n\n    if aspect_100 < 115:\n        candidate_flags |= C_FLAG_RELAXED_SHAPE\n        if density_100 < RELAXED_MIN_DENSITY_100:\n            return None\n        if width * 100 > RELAXED_MAX_WIDTH_PERCENT * FRAME_WIDTH:\n            return None\n        if box_area * 100 > RELAXED_MAX_AREA_PERCENT * frame_area:\n            return None\n\n    oversized = (\n        width > (48 * FRAME_WIDTH) // 100\n        or box_area > (28 * frame_area) // 100\n    )\n    if oversized and not (touches_top or touches_bottom):\n        return None\n\n    # Scores saturate. A huge colored background cannot win by pixels alone.\n    aspect_error = abs(aspect_100 - 200)\n    aspect_q ',
    b'= 100 - min(100, (100 * aspect_error) // 200)\n    density_q = clamp(\n        ((density_100 - MIN_DENSITY_100) * 100) // 48,\n        0,\n        100,\n    )\n    size_q = min(100, (pixels * 100) // 2500)\n    bottom_q = (base * 100) // (FRAME_HEIGHT - 1)\n    quality = (\n        45 * aspect_q\n        + 25 * density_q\n        + 15 * size_q\n        + 15 * bottom_q\n    ) // 100\n    if quality < MIN_CANDIDATE_QUALITY:\n        return None\n\n    return (\n        x,\n        y,\n        width,\n        height,\n        pixels,\n        density_100,\n        center_x,\n        base,\n        quality,\n        candidate_flags,\n    )\n\n\ndef copy_parking_blob(blob):\n    """Copy one magenta region without assuming pillar aspect ratio.\n\n    The two official parking limits are 200 x 20 x 100 mm and can present\n    either a broad side or a narrow end to the camera.  Until mounted-camera\n    measurements exist, no made-up aspect, scale, or pixel-gap limits are\n    used.  Safety instead comes from calibrated colour, existing hard frame\n    bo',
    b'unds, and joint three-frame pair tracking below.\n    """\n\n    x = int(blob.x())\n    y = int(blob.y())\n    width = int(blob.w())\n    height = int(blob.h())\n    pixels = int(blob.pixels())\n    density_100 = int(blob.density() * 100)\n\n    if width < 4 or height < 4 or pixels < MIN_PIXELS:\n        return None\n    if density_100 < MIN_DENSITY_100:\n        return None\n\n    right = x + width - 1\n    base = y + height - 1\n    if x < 0 or y < 0 or right >= FRAME_WIDTH or base >= FRAME_HEIGHT:\n        return None\n    center_x = x + (width - 1) // 2\n    if not base_on_ground(center_x, base):\n        return None\n\n    box_area = width * height\n    frame_area = FRAME_WIDTH * FRAME_HEIGHT\n    if box_area < MIN_AREA:\n        return None\n    if width * 100 > HARD_MAX_WIDTH_PERCENT * FRAME_WIDTH:\n        return None\n    if box_area * 100 > HARD_MAX_AREA_PERCENT * frame_area:\n        return None\n\n    # Density is the least assumptive per-object confidence available here;\n    # temporal and pair geometry decide presence, not thi',
    b's value by itself.\n    quality = clamp(density_100, 0, 100)\n    candidate_flags = (\n        C_FLAG_SIDE_CLIPPED\n        if x <= 3 or right >= FRAME_WIDTH - 4\n        else 0\n    )\n    return (\n        x,\n        y,\n        width,\n        height,\n        pixels,\n        density_100,\n        center_x,\n        base,\n        quality,\n        candidate_flags,\n    )\n\n\ndef candidate_seed_safe(candidate):\n    """Reject clipped/relaxed shapes when establishing a new identity."""\n\n    return candidate is not None and candidate[C_FLAGS] == 0\n\n\ndef candidate_rectangles_overlap(first, second):\n    """Return True when two candidate rectangles share at least one pixel."""\n\n    return not (\n        first[C_X] + first[C_W] <= second[C_X]\n        or second[C_X] + second[C_W] <= first[C_X]\n        or first[C_Y] + first[C_H] <= second[C_Y]\n        or second[C_Y] + second[C_H] <= first[C_Y]\n    )\n\n\ndef _candidate_contains_ground_point(candidate, other):\n    """Return True when ``other`` ends inside ``candidate``\'s silhouette."""\n\n',
    b'    return (\n        candidate[C_X]\n        <= other[C_CX]\n        < candidate[C_X] + candidate[C_W]\n        and candidate[C_Y]\n        <= other[C_BASE]\n        < candidate[C_Y] + candidate[C_H]\n    )\n\n\ndef reject_cross_color_ambiguity(red_candidates, green_candidates):\n    """Drop regions whose apparent ground contact has two colour identities.\n\n    Persisted thresholds are disjoint in LAB space, but adjacent fragmented\n    patches can still form overlapping red/green boxes around one scene\n    object.  A real steering instruction is not inferable in that geometry,\n    so both candidates fail closed for the current frame.\n    """\n\n    red_conflict = [False] * len(red_candidates)\n    green_conflict = [False] * len(green_candidates)\n    for red_index in range(len(red_candidates)):\n        red = red_candidates[red_index]\n        for green_index in range(len(green_candidates)):\n            green = green_candidates[green_index]\n            if _candidate_contains_ground_point(\n                red, green\n          ',
    b'  ) or _candidate_contains_ground_point(green, red):\n                red_conflict[red_index] = True\n                green_conflict[green_index] = True\n\n    return (\n        [\n            red_candidates[index]\n            for index in range(len(red_candidates))\n            if not red_conflict[index]\n        ],\n        [\n            green_candidates[index]\n            for index in range(len(green_candidates))\n            if not green_conflict[index]\n        ],\n    )\n\n\ndef keep_best_bounded(candidates, candidate):\n    """Keep at most MAX_CANDIDATES without an unbounded per-frame list."""\n\n    if len(candidates) < MAX_CANDIDATES:\n        candidates.append(candidate)\n        return\n\n    worst_index = 0\n    worst_rank = candidate_rank(candidates[0])\n    for index in range(1, len(candidates)):\n        rank = candidate_rank(candidates[index])\n        if rank < worst_rank:\n            worst_rank = rank\n            worst_index = index\n    if candidate_rank(candidate) > worst_rank:\n        candidates[worst_index] = cand',
    b'idate\n\n\ndef detect_candidates_checked(image, thresholds, copier=copy_blob):\n    """Return ``(candidates, scan_ok)`` and expose overload as a fault."""\n\n    candidates = []\n    if not track_roi_is_valid():\n        return candidates, False\n    blobs = image.find_blobs(\n        thresholds,\n        roi=TRACK_ROI,\n        x_stride=2,\n        y_stride=2,\n        pixels_threshold=MIN_PIXELS,\n        area_threshold=MIN_AREA,\n        merge=False,\n    )\n    if len(blobs) > MAX_RAW_BLOBS_PER_COLOR:\n        blobs = None\n        return candidates, False\n    require_ground_support = copier is copy_blob\n    for blob in blobs:\n        candidate = copier(blob)\n        if candidate is not None:\n            if require_ground_support and not candidate_has_ground_support(\n                image,\n                candidate,\n            ):\n                flagged = list(candidate)\n                flagged[C_FLAGS] |= C_FLAG_NO_GROUND_SUPPORT\n                candidate = tuple(flagged)\n            keep_best_bounded(candidates, candidate',
    b')\n    blobs = None\n    return candidates, True\n\n\ndef detect_candidates(image, thresholds):\n    """Compatibility wrapper for host tools that only need pillar boxes."""\n\n    return detect_candidates_checked(image, thresholds)[0]\n\n\ndef detect_parking_candidates(image, thresholds):\n    return detect_candidates_checked(image, thresholds, copy_parking_blob)\n\n\ndef detect_frame_candidates(\n    image,\n    red_thresholds,\n    green_thresholds,\n    magenta_thresholds,\n):\n    """Run the two required scans and an explicitly enabled optional third."""\n\n    red_candidates, red_scan_ok = detect_candidates_checked(\n        image,\n        red_thresholds,\n    )\n    green_candidates, green_scan_ok = detect_candidates_checked(\n        image,\n        green_thresholds,\n    )\n    if magenta_thresholds:\n        magenta_candidates, magenta_scan_ok = detect_parking_candidates(\n            image,\n            magenta_thresholds,\n        )\n    else:\n        magenta_candidates = []\n        magenta_scan_ok = True\n    return (\n        red_ca',
    b'ndidates,\n        green_candidates,\n        magenta_candidates,\n        red_scan_ok,\n        green_scan_ok,\n        magenta_scan_ok,\n    )\n\n\ndef update_candidate_trackers(\n    red_target,\n    green_target,\n    parking_pair,\n    red_candidates,\n    green_candidates,\n    magenta_candidates,\n    red_scan_ok,\n    green_scan_ok,\n    magenta_scan_ok,\n):\n    """Apply one frame while keeping optional parking health isolated.\n\n    Red and green are the required sensors for the current Obstacle profile.\n    A failed experimental magenta scan therefore clears only the parking pair;\n    it must never suppress an otherwise valid pillar observation.\n    """\n\n    pillar_scan_ok = red_scan_ok and green_scan_ok\n    if not pillar_scan_ok:\n        red_target.reset()\n        green_target.reset()\n        parking_pair.reset()\n        return [], [], [], False\n\n    red_candidates, green_candidates = reject_cross_color_ambiguity(\n        red_candidates,\n        green_candidates,\n    )\n    if magenta_scan_ok:\n        # When the option',
    b'al scan is enabled, a mixed red/magenta silhouette\n        # is not trustworthy as a red traffic sign. This catches a shadowed\n        # pink marker whose darker pixels enter the red band while its more\n        # saturated pixels remain in the safe magenta companion band.\n        original_magenta_candidates = magenta_candidates\n        red_candidates, magenta_without_red = reject_cross_color_ambiguity(\n            red_candidates,\n            original_magenta_candidates,\n        )\n        green_candidates, magenta_without_green = reject_cross_color_ambiguity(\n            green_candidates,\n            original_magenta_candidates,\n        )\n        magenta_candidates = [\n            candidate\n            for candidate in original_magenta_candidates\n            if candidate in magenta_without_red\n            and candidate in magenta_without_green\n        ]\n    red_target.update(red_candidates)\n    green_target.update(green_candidates)\n\n    if magenta_scan_ok:\n        parking_pair.update(magenta_candidates)\n    el',
    b'se:\n        magenta_candidates = []\n        parking_pair.reset()\n    return (\n        red_candidates,\n        green_candidates,\n        magenta_candidates,\n        True,\n    )\n\n\ndef best_global(candidates):\n    best = None\n    best_rank = -1\n    for candidate in candidates:\n        rank = candidate_rank(candidate)\n        if rank > best_rank:\n            best = candidate\n            best_rank = rank\n    return best\n\n\ndef best_seed_candidate(candidates):\n    """Choose the best complete, pillar-shaped candidate for a new track."""\n\n    best = None\n    best_rank = -1\n    for candidate in candidates:\n        if not candidate_seed_safe(candidate):\n            continue\n        rank = candidate_rank(candidate)\n        if rank > best_rank:\n            best = candidate\n            best_rank = rank\n    return best\n\n\nclass StableTarget:\n    """Fixed-size confirmed tracker with fail-closed occlusion memory."""\n\n    def __init__(self):\n        self.reset()\n\n    def reset(self):\n        self.alive = False\n        self.conf',
    b'irmed = False\n        self.hits = 0\n        self.misses = 0\n        self.x = 0\n        self.y = 0\n        self.w = 0\n        self.h = 0\n        self.q = 0\n        self.flags = 0\n\n    def clip_to_frame(self):\n        """Keep independently smoothed position and size inside the image."""\n\n        self.x = clamp(int(self.x), 0, FRAME_WIDTH - 1)\n        self.y = clamp(int(self.y), 0, FRAME_HEIGHT - 1)\n        self.w = clamp(int(self.w), 1, FRAME_WIDTH - self.x)\n        self.h = clamp(int(self.h), 1, FRAME_HEIGHT - self.y)\n\n    def seed(self, candidate):\n        self.alive = True\n        self.confirmed = TRACK_CONFIRM_HITS <= 1\n        self.hits = 1\n        self.misses = 0\n        self.x = candidate[C_X]\n        self.y = candidate[C_Y]\n        self.w = candidate[C_W]\n        self.h = candidate[C_H]\n        self.q = candidate[C_Q]\n        self.flags = candidate[C_FLAGS]\n        self.clip_to_frame()\n\n    def center_x(self):\n        return self.x + (self.w - 1) // 2\n\n    def base(self):\n        return min(FRAME_HEIGHT',
    b' - 1, self.y + self.h - 1)\n\n    def associated_candidate(self, candidates):\n        if not self.alive:\n            return None\n\n        old_cx = self.center_x()\n        old_base = self.base()\n        old_area = max(1, self.w * self.h)\n        best = None\n        best_distance = 100000\n        best_quality = -1\n\n        for candidate in candidates:\n            new_area = max(1, candidate[C_W] * candidate[C_H])\n            if max(old_area, new_area) > (\n                MAX_ASSOC_AREA_RATIO * min(old_area, new_area)\n            ):\n                continue\n\n            # A new or reacquired identity must overlap its previous box on\n            # every confirmation frame.  This prevents several unrelated\n            # small patches from chaining through the generous motion gate.\n            if self.hits < TRACK_CONFIRM_HITS:\n                if (\n                    self.x + self.w <= candidate[C_X]\n                    or candidate[C_X] + candidate[C_W] <= self.x\n                    or self.y + self.h <= candidate[',
    b'C_Y]\n                    or candidate[C_Y] + candidate[C_H] <= self.y\n                ):\n                    continue\n\n            dx = abs(candidate[C_CX] - old_cx)\n            db = abs(candidate[C_BASE] - old_base)\n            x_gate = min(\n                MAX_ASSOC_X_PX,\n                max(24, (3 * (candidate[C_W] + self.w)) // 4),\n            )\n            base_gate = min(\n                MAX_ASSOC_BASE_PX,\n                max(24, (candidate[C_H] + self.h) // 2),\n            )\n            if dx > x_gate or db > base_gate:\n                continue\n\n            # Continuity wins. Quality may break an exact distance tie, but a\n            # cleaner neighboring pillar cannot steal an established track.\n            distance = 2 * dx + db\n            if distance < best_distance or (\n                distance == best_distance and candidate[C_Q] > best_quality\n            ):\n                best = candidate\n                best_distance = distance\n                best_quality = candidate[C_Q]\n        return best\n',
    b'\n    def update(self, candidates):\n        if not self.alive:\n            candidate = best_seed_candidate(candidates)\n            if candidate is not None:\n                self.seed(candidate)\n            return\n\n        candidate = self.associated_candidate(candidates)\n        if candidate is not None:\n            # Integer EMA: 55% previous state, 45% new measurement.\n            self.x = (55 * self.x + 45 * candidate[C_X] + 50) // 100\n            self.y = (55 * self.y + 45 * candidate[C_Y] + 50) // 100\n            self.w = (55 * self.w + 45 * candidate[C_W] + 50) // 100\n            self.h = (55 * self.h + 45 * candidate[C_H] + 50) // 100\n            self.q = (55 * self.q + 45 * candidate[C_Q] + 50) // 100\n            # Geometry is smoothed for stability, but confidence flags always\n            # describe the current measurement. In particular, a newly\n            # clipped parking edge must not remain actionable through EMA.\n            self.flags = candidate[C_FLAGS]\n            # Position and size are ro',
    b'unded separately. Two valid boxes that\n            # both touch an image edge can otherwise produce a smoothed box\n            # one pixel outside the frame.\n            self.clip_to_frame()\n            self.hits = min(255, self.hits + 1)\n            self.misses = 0\n            if self.hits >= TRACK_CONFIRM_HITS:\n                self.confirmed = True\n            return\n\n        self.misses = min(255, self.misses + 1)\n        # Any gap requires a complete fresh confirmation chain before this\n        # old identity can become actionable again.\n        self.hits = 0\n        if not self.confirmed:\n            if self.misses >= UNCONFIRMED_MISS_LIMIT:\n                replacement = best_seed_candidate(candidates)\n                self.reset()\n                if replacement is not None:\n                    self.seed(replacement)\n            return\n\n        if self.misses > TRACK_OCCLUSION_MEMORY_FRAMES:\n            replacement = best_seed_candidate(candidates)\n            self.reset()\n            if replacement is no',
    b't None:\n                self.seed(replacement)\n\n    def visible(self):\n        return (\n            self.alive\n            and self.confirmed\n            and self.misses <= TRACK_OCCLUSION_MEMORY_FRAMES\n        )\n\n    def actionable(self):\n        return (\n            self.visible()\n            and self.misses == 0\n            and self.hits >= TRACK_CONFIRM_HITS\n        )\n\n\ndef ordered_parking_pair(candidates):\n    """Return the only unambiguous two-marker image pair, or ``None``.\n\n    Protocol V1 has named left/right slots but no generic-magenta slot.  More\n    or fewer than two regions therefore cannot be assigned honestly.  The two\n    boxes must also be distinct horizontally and overlap vertically; otherwise\n    they do not visibly delimit one parking opening in this frame. Left/right\n    here is screen-X ordering only, not a claim about the physical bay sides.\n    This remains experimental telemetry, not a parking-control decision.\n    """\n\n    if len(candidates) != 2:\n        return None\n    first = can',
    b'didates[0]\n    second = candidates[1]\n    if first[C_CX] == second[C_CX]:\n        return None\n    if first[C_CX] < second[C_CX]:\n        left, right = first, second\n    else:\n        left, right = second, first\n\n    if left[C_X] + left[C_W] > right[C_X]:\n        return None\n    if (\n        left[C_Y] + left[C_H] <= right[C_Y]\n        or right[C_Y] + right[C_H] <= left[C_Y]\n    ):\n        return None\n    return left, right\n\n\nclass ParkingPairTracker:\n    """Two fixed tracks that only expose a fresh, jointly confirmed pair."""\n\n    def __init__(self):\n        self.left = StableTarget()\n        self.right = StableTarget()\n\n    def reset(self):\n        self.left.reset()\n        self.right.reset()\n\n    def _miss_pair(self):\n        self.left.update([])\n        self.right.update([])\n        # Keep the two identities atomic.  If either expires, the other must\n        # not survive and later combine with an unrelated marker.\n        if self.left.alive != self.right.alive:\n            self.reset()\n\n    def update(self',
    b', candidates):\n        pair = ordered_parking_pair(candidates)\n        if pair is None:\n            self._miss_pair()\n            return\n        left_candidate, right_candidate = pair\n\n        if not self.left.alive and not self.right.alive:\n            if candidate_seed_safe(left_candidate) and candidate_seed_safe(\n                right_candidate\n            ):\n                self.left.seed(left_candidate)\n                self.right.seed(right_candidate)\n            return\n        if not self.left.alive or not self.right.alive:\n            self.reset()\n            return\n\n        # Screen ordering makes assignment one-to-one and prevents both\n        # tracks from selecting the same blob.  Each child still applies its\n        # bounded area/motion and confirmation-overlap gates.\n        left_match = self.left.associated_candidate([left_candidate])\n        right_match = self.right.associated_candidate([right_candidate])\n        if left_match is None or right_match is None:\n            self._miss_pair()\n     ',
    b'       return\n        self.left.update([left_match])\n        self.right.update([right_match])\n\n    def visible(self):\n        return self.left.visible() and self.right.visible()\n\n    def actionable(self):\n        if not self.left.actionable() or not self.right.actionable():\n            return False\n        if self.left.flags != 0 or self.right.flags != 0:\n            return False\n        if self.left.center_x() >= self.right.center_x():\n            return False\n        if self.left.x + self.left.w > self.right.x:\n            return False\n        return not (\n            self.left.y + self.left.h <= self.right.y\n            or self.right.y + self.right.h <= self.left.y\n        )\n\n    def targets(self):\n        if not self.actionable():\n            return None, None\n        return self.left, self.right\n\n\ndef draw_raw_candidates(image, candidates, color):\n    for candidate in candidates:\n        image.draw_rectangle(\n            candidate[C_X],\n            candidate[C_Y],\n            candidate[C_W],\n            ',
    b'candidate[C_H],\n            color=color,\n            thickness=1,\n        )\n        image.draw_cross(\n            candidate[C_CX],\n            candidate[C_BASE],\n            color=color,\n            size=3,\n            thickness=1,\n        )\n\n\ndef draw_target(image, name, target, color, top_y, instruction):\n    if not target.visible():\n        return\n\n    fresh = target.actionable()\n    draw_color = color if fresh else (255, 255, 0)\n    center_x = target.center_x()\n    base = target.base()\n    x_milli = ((2 * center_x - (FRAME_WIDTH - 1)) * 1000) // (\n        FRAME_WIDTH - 1\n    )\n\n    image.draw_rectangle(\n        target.x,\n        target.y,\n        target.w,\n        target.h,\n        color=draw_color,\n        thickness=3 if fresh else 1,\n    )\n    image.draw_cross(\n        center_x,\n        base,\n        color=draw_color,\n        size=6 if fresh else 3,\n        thickness=2 if fresh else 1,\n    )\n\n    label_y = target.y - 11\n    if label_y < 0:\n        label_y = min(FRAME_HEIGHT - 10, target.y + 2)\n    image',
    b'.draw_string_advanced(\n        clamp(target.x, 0, FRAME_WIDTH - 120),\n        label_y,\n        8,\n        "%s x=%d b=%d e=%+d" % (name[0], center_x, base, x_milli),\n        color=draw_color,\n    )\n    image.draw_string_advanced(\n        2,\n        top_y,\n        8,\n        "%s %s" % (name, instruction if fresh else "STALE - HOLD"),\n        color=draw_color,\n    )\n\n\ndef draw_vision_status(image, vision_ok, l_uq, l_max):\n    if vision_ok:\n        image.draw_string_advanced(\n            2,\n            22,\n            8,\n            "VISION OK Lq=%d Lmax=%d" % (l_uq, l_max),\n            color=(255, 255, 255),\n        )\n    else:\n        image.draw_string_advanced(\n            2,\n            22,\n            12,\n            "VISION BAD - ADD WHITE LIGHT",\n            color=(255, 255, 0),\n        )\n        image.draw_string_advanced(\n            2,\n            36,\n            8,\n            "Lq=%d Lmax=%d - NO TARGET OUTPUT" % (l_uq, l_max),\n            color=(255, 255, 0),\n        )\n\n\ndef target_telemetry(name, tar',
    b'get):\n    if not target.visible():\n        return "%s ok=0" % name[0]\n\n    center_x = target.center_x()\n    base = target.base()\n    x_milli = ((2 * center_x - (FRAME_WIDTH - 1)) * 1000) // (\n        FRAME_WIDTH - 1\n    )\n    base_milli = (base * 1000) // (FRAME_HEIGHT - 1)\n    return (\n        "%s ok=1 act=%d fresh=%d box=%d,%d,%d,%d aim=%d,%d "\n        "x_m=%+d base_m=%d q=%d"\n        % (\n            name[0],\n            1 if target.actionable() else 0,\n            1 if target.misses == 0 else 0,\n            target.x,\n            target.y,\n            target.w,\n            target.h,\n            center_x,\n            base,\n            x_milli,\n            base_milli,\n            target.q,\n        )\n    )\n\n\ndef main():\n    global RED_LAB, GREEN_LAB, MAGENTA_LAB\n    global RED_THRESHOLDS, GREEN_THRESHOLDS, MAGENTA_THRESHOLDS\n\n    import os\n    import time\n\n    from media.display import Display\n    from media.media import MediaManager\n    from media.sensor import Sensor\n\n    sensor = None\n    sensor_running = F',
    b'alse\n    display_ready = False\n    media_ready = False\n    image = None\n    statistics = None\n    red_candidates = None\n    green_candidates = None\n    magenta_candidates = None\n    uart_link = None\n    last_heartbeat_tick = None\n\n    red_target = StableTarget()\n    green_target = StableTarget()\n    parking_pair = ParkingPairTracker()\n    vision_ok = False\n    vision_l_uq = 0\n    vision_l_max = 0\n\n    os.exitpoint(os.EXITPOINT_ENABLE)\n\n    RED_LAB, GREEN_LAB, MAGENTA_LAB, color_config_source = load_color_thresholds()\n    RED_THRESHOLDS = [RED_LAB]\n    GREEN_THRESHOLDS = [GREEN_LAB]\n    MAGENTA_THRESHOLDS = (\n        magenta_detection_thresholds(RED_LAB, GREEN_LAB, MAGENTA_LAB)\n        if ENABLE_EXPERIMENTAL_PARKING_TELEMETRY\n        and MAGENTA_LAB is not None\n        else []\n    )\n    calibration_ready = persisted_pillar_config_ready(\n        color_config_source,\n    ) and track_roi_is_valid()\n    print("colour thresholds loaded from:", color_config_source)\n    print("magenta LAB:", MAGENTA_LAB if MAGENTA_LA',
    b'B is not None else "not calibrated")\n    if calibration_ready:\n        print("PERSISTED COLOR CONFIG LOADED: field detection not yet proven")\n        print(\n            "EXPERIMENTAL PARKING TELEMETRY: %s"\n            % (\n                "enabled (image-left/image-right; unvalidated)"\n                if MAGENTA_THRESHOLDS\n                else "disabled"\n            )\n        )\n    else:\n        print(\n            "OBSTACLE CALIBRATION INVALID: preview only; target UART "\n            "slots disabled"\n        )\n\n    try:\n        if ENABLE_UART_LINK:\n            try:\n                uart_link = open_uart_link()\n                boot_tick = time.ticks_ms()\n                boot_ok = uart_send_boot_heartbeat(uart_link, boot_tick)\n                last_heartbeat_tick = boot_tick\n                print(\n                    "UART2 telemetry enabled: GPIO%d TX / GPIO%d RX, "\n                    "115200 8N1"\n                    % (UART_TX_GPIO, UART_RX_GPIO)\n                )\n                if not boot_ok:\n               ',
    b'     print(\n                        "UART BOOT heartbeat incomplete; ESP32 must ignore "\n                        "the link until a valid heartbeat"\n                    )\n            except Exception as error:\n                # Camera bench testing remains available if an explicitly\n                # enabled link cannot initialize. No target leaves the board.\n                uart_link = None\n                print("UART2 telemetry unavailable:", error)\n\n        sensor = Sensor(width=FRAME_WIDTH, height=FRAME_HEIGHT, fps=30)\n        sensor.reset()\n        sensor.set_framesize(width=FRAME_WIDTH, height=FRAME_HEIGHT)\n        sensor.set_pixformat(Sensor.RGB565)\n\n        if ENABLE_IDE_PREVIEW:\n            Display.init(\n                Display.VIRT,\n                width=FRAME_WIDTH,\n                height=FRAME_HEIGHT,\n                fps=PREVIEW_FPS,\n                to_ide=True,\n                quality=50,\n                osd_num=1,\n            )\n            display_ready = True\n        MediaManager.init()\n        ',
    b'media_ready = True\n        sensor.run()\n        sensor_running = True\n\n        # Let automatic exposure and white balance settle before reporting.\n        for _ in range(25):\n            image = sensor.snapshot()\n            image = None\n            time.sleep_ms(20)\n\n        print("BUBBLEGUM fail-closed obstacle vision started")\n        print("sensor type:", sensor.get_type())\n        print("red LAB:", RED_LAB)\n        print("green LAB:", GREEN_LAB)\n        print("position units: pixels plus normalized thousandths; not cm")\n\n        clock = time.clock()\n        frame_number = 0\n        previous_cycle_age_ms = 0\n        scan_ok = True\n\n        while True:\n            os.exitpoint()\n            clock.tick()\n            frame_number += 1\n            capture_tick = time.ticks_ms()\n            image = sensor.snapshot()\n\n            if frame_number == 1 or (\n                frame_number % VISION_CHECK_INTERVAL == 0\n            ):\n                statistics = image.get_statistics()\n                vision_ok, vision',
    b'_l_uq, vision_l_max = vision_quality(\n                    statistics\n                )\n                statistics = None\n                if not vision_ok:\n                    red_target.reset()\n                    green_target.reset()\n                    parking_pair.reset()\n\n            scan_ok = True\n            detection_requested = calibration_ready or ENABLE_IDE_PREVIEW\n            if vision_ok and detection_requested:\n                # All scans happen before any debug overlays are drawn.  An\n                # invalid/overloaded pillar scan is different from a healthy\n                # frame containing no target, so it degrades the observation.\n                # Optional magenta failure is isolated by the update helper.\n                (\n                    red_candidates,\n                    green_candidates,\n                    magenta_candidates,\n                    red_scan_ok,\n                    green_scan_ok,\n                    magenta_scan_ok,\n                ) = detect_frame_candidates(\n      ',
    b'              image,\n                    RED_THRESHOLDS,\n                    GREEN_THRESHOLDS,\n                    MAGENTA_THRESHOLDS,\n                )\n                (\n                    red_candidates,\n                    green_candidates,\n                    magenta_candidates,\n                    scan_ok,\n                ) = update_candidate_trackers(\n                    red_target,\n                    green_target,\n                    parking_pair,\n                    red_candidates,\n                    green_candidates,\n                    magenta_candidates,\n                    red_scan_ok,\n                    green_scan_ok,\n                    magenta_scan_ok,\n                )\n            else:\n                red_candidates = []\n                green_candidates = []\n                magenta_candidates = []\n                red_target.reset()\n                green_target.reset()\n                parking_pair.reset()\n\n            if uart_link is not None:\n                # The frame header carries cap',
    b"ture time; receipt time remains\n                # the ESP32's freshness authority because clocks are separate.\n                uart_now_tick = time.ticks_ms()\n                # Include the full-frame 8N1 serialization budget so age at\n                # the ESP32 is conservative even though the two clocks are\n                # unrelated and UART.write() may return after queueing bytes.\n                processing_age_ms = clamp(\n                    time.ticks_diff(uart_now_tick, capture_tick)\n                    + UART_OBSERVATION_WIRE_TIME_MS,\n                    0,\n                    0xFFFF,\n                )\n                cycle_overrun = (\n                    processing_age_ms > PIPELINE_OVERRUN_AGE_MS\n                    or previous_cycle_age_ms > PIPELINE_OVERRUN_AGE_MS\n                )\n                heartbeat_state, heartbeat_error_flags = uart_health_status(\n                    vision_ok,\n                    calibration_ready,\n                    scan_ok,\n                    cycle_overrun,\n        ",
    b'        )\n                pipeline_valid = heartbeat_state == UART_STATE_READY\n                magenta_left_target, magenta_right_target = (\n                    parking_pair.targets()\n                )\n                observation = uart_pack_tracker_observation(\n                    pipeline_valid,\n                    uart_frame_quality(\n                        pipeline_valid,\n                        vision_l_uq,\n                        vision_l_max,\n                    ),\n                    processing_age_ms,\n                    red_target,\n                    green_target,\n                    # Current processing age cannot include work performed\n                    # after this packet is formed (notably IDE preview). Carry\n                    # the complete previous-cycle duration forward so a USB\n                    # display stall still lowers the ESP32 speed envelope on\n                    # the following observation.\n                    pipeline_overrun=cycle_overrun,\n                    magenta_left_t',
    b'arget=magenta_left_target,\n                    magenta_right_target=magenta_right_target,\n                    exposure_unstable=not vision_ok,\n                )\n                observation_ok = uart_link.send(\n                    UART_TYPE_OBSERVATION,\n                    capture_tick & 0xFFFFFFFF,\n                    observation,\n                )\n\n                if last_heartbeat_tick is None or time.ticks_diff(\n                    uart_now_tick,\n                    last_heartbeat_tick,\n                ) >= UART_HEARTBEAT_INTERVAL_MS:\n                    last_heartbeat_tick = uart_now_tick\n                    heartbeat = uart_pack_heartbeat(\n                        heartbeat_state,\n                        error_flags=heartbeat_error_flags,\n                        loop_rate_hz_x10=clamp(\n                            int(clock.fps() * 10),\n                            0,\n                            0xFFFF,\n                        ),\n                    )\n                    heartbeat_ok = uart_link.send(\n     ',
    b'                   UART_TYPE_HEARTBEAT,\n                        uart_now_tick & 0xFFFFFFFF,\n                        heartbeat,\n                    )\n                else:\n                    heartbeat_ok = True\n\n                if not observation_ok or not heartbeat_ok:\n                    # UART errors are absorbed and counters saturate. Log only\n                    # the first few and sparse milestones to avoid a print\n                    # storm making the camera loop worse.\n                    error_count = uart_link.write_errors\n                    if error_count <= 3 or error_count % 100 == 0:\n                        print(\n                            "UART write incomplete; link data ignored, "\n                            "errors=%d streak=%d"\n                            % (error_count, uart_link.write_error_streak)\n                        )\n\n            if ENABLE_IDE_PREVIEW:\n                # Thin boxes are valid current-frame objects. Thick boxes are\n                # fresh, stable targets; stale gr',
    b'ace frames are yellow and\n                # never actionable for future control.\n                draw_raw_candidates(image, red_candidates, (255, 0, 0))\n                draw_raw_candidates(image, green_candidates, (0, 255, 0))\n                draw_raw_candidates(\n                    image,\n                    magenta_candidates,\n                    (255, 0, 255),\n                )\n                draw_target(\n                    image,\n                    "RED",\n                    red_target,\n                    (255, 0, 0),\n                    2,\n                    "KEEP RIGHT",\n                )\n                draw_target(\n                    image,\n                    "GREEN",\n                    green_target,\n                    (0, 255, 0),\n                    12,\n                    "KEEP LEFT",\n                )\n                draw_target(\n                    image,\n                    "MAGENTA-IMG-L",\n                    parking_pair.left,\n                    (255, 0, 255),\n                    46,',
    b'\n                    "EXPERIMENTAL",\n                )\n                draw_target(\n                    image,\n                    "MAGENTA-IMG-R",\n                    parking_pair.right,\n                    (255, 0, 255),\n                    56,\n                    "EXPERIMENTAL",\n                )\n                draw_vision_status(\n                    image,\n                    vision_ok,\n                    vision_l_uq,\n                    vision_l_max,\n                )\n\n                # Detection runs every frame; debug preview is rate-limited to\n                # avoid USB/webview backpressure.\n                if frame_number % PREVIEW_DIVISOR == 0:\n                    Display.show_image(image)\n\n            if frame_number % 60 == 0:\n                print(\n                    "fps=%.1f vision=%d cfg=%d scan=%d Lq=%d Lmax=%d "\n                    "mem=%d raw=%d/%d/%d | %s | %s | pair=%d"\n                    % (\n                        clock.fps(),\n                        1 if vision_ok else 0,\n        ',
    b'                1 if calibration_ready else 0,\n                        1 if scan_ok else 0,\n                        vision_l_uq,\n                        vision_l_max,\n                        gc.mem_free(),\n                        len(red_candidates),\n                        len(green_candidates),\n                        len(magenta_candidates),\n                        target_telemetry("RED", red_target),\n                        target_telemetry("GREEN", green_target),\n                        1 if parking_pair.actionable() else 0,\n                    )\n                )\n\n            if frame_number % 120 == 0:\n                gc.collect()\n\n            previous_cycle_age_ms = clamp(\n                time.ticks_diff(time.ticks_ms(), capture_tick),\n                0,\n                0xFFFF,\n            )\n\n    except KeyboardInterrupt:\n        print("pillar tracker stopped by user")\n    except BaseException as error:\n        if str(error) == "IDE interrupt":\n            print("pillar tracker stopped by IDE")\n      ',
    b'  else:\n            print("pillar tracker error:", error)\n            raise\n    finally:\n        # Drop per-frame references before releasing the MPP/VB pipeline.\n        statistics = None\n        red_candidates = None\n        green_candidates = None\n        magenta_candidates = None\n        image = None\n        cleanup_failed = False\n\n        if uart_link is not None:\n            uart_link.close()\n            uart_link = None\n\n        if sensor_running:\n            try:\n                sensor.stop()\n            except BaseException as error:\n                cleanup_failed = True\n                print("sensor cleanup failed:", error)\n        if display_ready:\n            try:\n                Display.deinit()\n            except BaseException as error:\n                cleanup_failed = True\n                print("display cleanup failed:", error)\n        os.exitpoint(os.EXITPOINT_ENABLE_SLEEP)\n        time.sleep_ms(100)\n        if media_ready:\n            try:\n                MediaManager.deinit()\n            exc',
    b'ept BaseException as error:\n                cleanup_failed = True\n                print("media cleanup failed:", error)\n        gc.collect()\n        if cleanup_failed:\n            print("cleanup incomplete: restart the K230 before retrying")\n        else:\n            print(\n                "camera pipeline stopped; if the next init reports error 18, "\n                "restart the K230"\n            )\n\n\nif __name__ == "__main__":\n    main()\n',
)


def _sync():
    """Flush filesystem metadata when this firmware exposes os.sync."""
    try:
        os.sync()
    except (AttributeError, OSError):
        pass


def _exists(path):
    try:
        os.stat(path)
        return True
    except OSError:
        return False


def _remove_if_present(path):
    if _exists(path):
        os.remove(path)


def _file_identity(path):
    digest = hashlib.sha256()
    size = 0
    handle = open(path, "rb")
    try:
        while True:
            block = handle.read(1024)
            if not block:
                break
            size += len(block)
            digest.update(block)
    finally:
        handle.close()
    return size, digest.digest()


def _verified(path):
    size, digest = _file_identity(path)
    return size == EXPECTED_SIZE and digest == EXPECTED_SHA256


def install():
    moved_old = False
    installed_new = False
    print("INSTALL START: BUBBLEGUM K230 production main.py")
    print("target:", TARGET_PATH)
    print("expected bytes:", EXPECTED_SIZE)
    print("expected sha256:", EXPECTED_SHA256_HEX)

    try:
        _remove_if_present(TEMP_PATH)

        digest = hashlib.sha256()
        total = 0
        handle = open(TEMP_PATH, "wb")
        try:
            for chunk in PAYLOAD_CHUNKS:
                written = handle.write(chunk)
                if written is not None and written != len(chunk):
                    raise OSError("short write")
                total += len(chunk)
                digest.update(chunk)
            handle.flush()
        finally:
            handle.close()
        _sync()

        if total != EXPECTED_SIZE or digest.digest() != EXPECTED_SHA256:
            raise ValueError("embedded payload verification failed")
        if not _verified(TEMP_PATH):
            raise ValueError("SD-card read-back verification failed")

        if _exists(TARGET_PATH):
            _remove_if_present(BACKUP_PATH)
            os.rename(TARGET_PATH, BACKUP_PATH)
            moved_old = True
            _sync()

        os.rename(TEMP_PATH, TARGET_PATH)
        installed_new = True
        _sync()
        if not _verified(TARGET_PATH):
            raise ValueError("installed main.py verification failed")

        print("INSTALL OK: /sdcard/main.py VERIFIED")
        print("installed bytes:", EXPECTED_SIZE)
        print("installed sha256:", EXPECTED_SHA256_HEX)
        if moved_old:
            print("previous main.py retained as:", BACKUP_PATH)
        print("RESTART K230 TO LOAD /sdcard/main.py")
        return True

    except Exception as error:
        print("INSTALL FAILED:", error)
        try:
            _remove_if_present(TEMP_PATH)
        except Exception as cleanup_error:
            print("temporary-file cleanup failed:", cleanup_error)

        if moved_old:
            try:
                _remove_if_present(TARGET_PATH)
                if _exists(BACKUP_PATH):
                    os.rename(BACKUP_PATH, TARGET_PATH)
                    _sync()
                    if _exists(TARGET_PATH):
                        print("OLD main.py RESTORED")
                    else:
                        print("OLD main.py RESTORE FAILED; backup may remain")
                else:
                    print("OLD main.py RESTORE FAILED; backup is missing")
            except Exception as restore_error:
                print("OLD main.py RESTORE FAILED:", restore_error)
                print("check retained backup:", BACKUP_PATH)
        elif installed_new:
            try:
                _remove_if_present(TARGET_PATH)
                _sync()
                print("INVALID new main.py REMOVED")
            except Exception as cleanup_error:
                print("INVALID new main.py CLEANUP FAILED:", cleanup_error)
        else:
            print("existing main.py was not replaced")
        return False


if __name__ == "__main__":
    install()
